---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 18.20.7-alpine

params:
  APPLICATION:

inputs:
  - name: explore-local-statistics-app

outputs:
  - name: build

run:
  path: explore-local-statistics-app/ci/scripts/build.sh
